name: Generate data and deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout pru-lights
        uses: actions/checkout@v4
        with:
          repository: ErinMorelli/pru-lights
          path: pru-lights
          token: ${{ secrets.GH_PAT }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt && pip install ./pru-lights

      - run: python scripts/generate_data.py data.json

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          exclude_assets: '.github,scripts,pru-lights,requirements.txt,README.md,.gitignore'
          keep_files: false
          cname: prudentialcenterlights.today
